wallpaper {
    monitor = DP-3
    path = ~/Pictures/Wallpaper/wallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = ~/Pictures/Wallpaper/wallpaper.png
    fit_mode = cover
}
