$mainMod = SUPER
###################
### MY PROGRAMS ###
###################
$terminal = ghostty
$fileManager = dolphin
$menu = vicinae toggle

#################
### AUTOSTART ###
#################
source = ~/.config/hypr/configs/autostart.conf

###############
### VICINAE ###
###############
source = ~/.config/hypr/configs/vicinae.conf

###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/configs/keybinds.conf

#############
### INPUT ###
#############
source = ~/.config/hypr/configs/input.conf

################
### MONITORS ###
################
source = ~/.config/hypr/configs/monitor.conf

#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/configs/looks.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
source = ~/.config/hypr/configs/windowrules.conf
source = ~/.config/hypr/configs/workspaces.conf