# Monitors (Dell centered, Samsung bottom right)
source = ~/.config/hypr/configs/monitor.conf

# General Looks
source = ~/.config/hypr/configs/looks.conf

# Decorations
source = ~/.config/hypr/configs/decorations.conf

# Colors (Pastel theme)
source = ~/.config/hypr/configs/colors.conf

# Input
source = ~/.config/hypr/configs/input.conf

# Keybinds
source = ~/.config/hypr/configs/keybinds.conf

# Start Programs
source = ~/.config/hypr/configs/autostart.conf

# Window Rules
source = ~/.config/hypr/configs/windowrules.conf

# Workspace Config
source = ~/.config/hypr/configs/workspaces.conf