# Start Waybar
exec-once = waybar

# Disable sleep
exec-once = hyprctl dispatch dpms on

#
exec-once = hyprpaper

# hyprpolkitagent is a polkit authentication daemon. It is required for GUI applications to be able to request elevated privileges.
exec-once = systemctl --user start hyprpolkitagent

# cliphist Clipboard Managers
# exec-once = wl-paste --type text --watch cliphist store 
# exec-once = wl-paste --type image --watch cliphist store

# Cursor Clip Clipboard manager
exec-once = cursor-clip --daemon
