# Start Waybar
exec-once = waybar

# Disable sleep
exec-once = hyprctl dispatch dpms on

# Wall Paper
exec-once = awww-daemon
exec-once = waypaper --restore

# hyprpolkitagent is a polkit authentication daemon. It is required for GUI applications to be able to request elevated privileges.
exec-once = systemctl --user start hyprpolkitagent

# Launcher 
exec-once = vicinae server

# Cursor Clip Clipboard manager
exec-once = cursor-clip --daemon
